import type { WorkerManifest } from '../../types';

export const emailChannelWorker: WorkerManifest = {
  manifestVersion: 1,
  bfrostApiVersion: '0.1',
  id: 'core.channels.email',
  name: 'Email Channel',
  displayName: 'Email',
  version: '0.1.0',
  description: 'Send operator notifications via SMTP. Connect-flow auto-detects Gmail, Fastmail, iCloud, and Outlook settings.',
  tagline: 'Have BFrost email you when a job runs, fails, or needs your attention — works with any email provider.',
  builtIn: true,
  kind: 'channel',
  requiredCredentials: [
    { key: 'emailConfigured', label: 'SMTP credentials', settingsTarget: 'config' },
  ],
  ownedSettings: [
    {
      key: 'email-credentials',
      label: 'Email credentials',
      description: 'SMTP and IMAP server settings.',
      scope: 'global',
      storageKey: 'kv:core.channels.email.credentials',
      dashboardTarget: 'config',
    },
  ],
  jobs: [],
  dashboard: {
    settings: [
      {
        id: 'email-credentials',
        label: 'Email credentials',
        description: 'SMTP settings for sending notifications. IMAP settings for the inbox verifier.',
        tab: 'config',
        path: '/api/workers/email/settings',
        fields: [
          {
            key: 'emailAddress',
            label: 'Your email address',
            type: 'text' as const,
            defaultValue: '',
            placeholder: 'you@example.com',
            helpText: 'Used as the From address when sending notifications.',
          },
          {
            key: 'notifyAddress',
            label: 'Notify address (optional)',
            type: 'text' as const,
            defaultValue: '',
            placeholder: 'you@example.com',
            helpText: 'Where BFrost sends notifications. Defaults to your email address if left blank.',
          },
          {
            key: 'smtpHost',
            label: 'SMTP host',
            type: 'text' as const,
            defaultValue: '',
            placeholder: 'smtp.gmail.com',
          },
          {
            key: 'smtpPort',
            label: 'SMTP port',
            type: 'number' as const,
            defaultValue: 587,
            helpText: '587 with STARTTLS is recommended. Port 465 with SSL/TLS may fail on some networks.',
          },
          {
            key: 'smtpUser',
            label: 'SMTP username',
            type: 'text' as const,
            defaultValue: '',
            placeholder: 'you@example.com',
          },
          {
            key: 'smtpPassword',
            label: 'SMTP password / App password',
            type: 'secret-reference' as const,
            defaultValue: '',
            helpText: 'Gmail: go to myaccount.google.com/apppasswords, choose "Other (Custom name)", copy the 16-digit password. iCloud and Fastmail also require an App Password.',
          },
          {
            key: 'imapHost',
            label: 'IMAP host',
            type: 'text' as const,
            defaultValue: '',
            placeholder: 'imap.gmail.com',
          },
          {
            key: 'imapPort',
            label: 'IMAP port',
            type: 'number' as const,
            defaultValue: 993,
            helpText: '993 for SSL/TLS (recommended).',
          },
          {
            key: 'imapUser',
            label: 'IMAP username',
            type: 'text' as const,
            defaultValue: '',
            placeholder: 'you@example.com',
          },
          {
            key: 'imapPassword',
            label: 'IMAP password / App password',
            type: 'secret-reference' as const,
            defaultValue: '',
            helpText: 'Usually the same as your SMTP password.',
          },
          {
            key: 'imapMailbox',
            label: 'IMAP mailbox',
            type: 'text' as const,
            defaultValue: 'INBOX',
            helpText: 'The mailbox to check. Default: INBOX.',
          },
        ],
      },
    ],
  },
  channels: [
    {
      id: 'email',
      workerId: 'core.channels.email',
      label: 'Email',
      description: 'Email channel adapter — sends operator notifications via SMTP.',
      capabilities: {
        text: true,
        image: false,
        audio: false,
        files: false,
        markdown: false,
        buttons: false,
      },
    },
  ],
};
