import {
  DEFAULT_NEWS_INTERESTS,
  DEFAULT_NEWS_DIGEST_PARAMS,
  NewsDigestParamsSchema,
  runNewsDigest,
} from './job';
import type { WorkerManifest } from '../../types';

const NEWS_INTEREST_SUGGESTIONS = [
  'World news',
  'Local news',
  'Technology news',
  'Business news',
  'Markets and finance',
  'Science',
  'Climate and environment',
  'Health',
  'Education',
  'Culture',
  'Sports',
  'Travel',
  'AI and software',
  'Startups',
];

// Built-in workers are the contributor reference path: keep behavior in
// worker folders, then describe ownership, defaults, health, and dashboard
// fields beside that behavior so core scheduler/UI code stays generic.
export const newsWorker: WorkerManifest = {
  id: 'core.news',
  name: 'News',
  displayName: 'Daily News Digest',
  version: '0.1.0',
  description: 'Collects, evaluates, deduplicates, and queues news digest items.',
  tagline: 'Pulls articles from sources you choose, scores them for quality, and queues a short digest you can review before anything else uses it.',
  builtIn: true,
  requiredCredentials: [
    { key: 'googleSearchConfigured', label: 'Google Search credentials', settingsTarget: 'health-google' },
  ],
  optionalDependencies: [
    { key: 'sqliteCli', label: 'SQLite CLI', settingsTarget: 'health-dependencies' },
  ],
  ownedSettings: [
    {
      key: 'news-digest-job',
      label: 'News digest schedule',
      description: 'Cron, model, prompt, and parameter settings for the news digest job.',
      scope: 'job',
      storageKey: 'admin.settings.jobs.news-digest',
      dashboardTarget: 'jobs',
    },
    {
      key: 'google-search-credentials',
      label: 'Google Search credentials',
      description: 'Local environment values used by the News worker for Google Custom Search.',
      scope: 'worker',
      storageKey: '.env.GOOGLE_*',
      dashboardTarget: 'config',
    },
    {
      key: 'source-quality-rules',
      label: 'Source quality rules',
      description: 'Host allow/block/preference rules used before queueing digest items.',
      scope: 'worker',
      storageKey: 'source.rules',
      dashboardTarget: 'queue',
    },
  ],
  dashboard: {
    settings: [
      {
        id: 'google-credentials',
        label: 'Google Search credentials',
        description: 'API key and search engine ID used by the News worker.',
        tab: 'config',
        path: '/api/google-credentials',
        fields: [
          {
            key: 'googleApiKey',
            label: 'Google API key',
            type: 'secret-reference',
            defaultValue: '',
            placeholder: 'Configured in local .env',
            helpText: 'Stored as GOOGLE_API_KEY. Leave blank to keep the current value.',
          },
          {
            key: 'googleSearchEngineId',
            label: 'Search engine ID',
            type: 'text',
            defaultValue: '',
            helpText: 'Stored as GOOGLE_SEARCH_ENGINE_ID. Leave blank to keep the current value.',
          },
        ],
      },
      {
        id: 'source-quality-rules',
        label: 'Source quality rules',
        description: 'Allow, block, and score source hosts before digest items enter the queue.',
        tab: 'config',
        path: '/api/source-rules',
        fields: [
          {
            key: 'minScore',
            label: 'Minimum score',
            type: 'number',
            defaultValue: 0,
            helpText: 'Reject sources scoring below this value unless they are allowlisted.',
            seedPath: 'core.news.sourceRules.minScore',
          },
          {
            key: 'allowHosts',
            label: 'Allow hosts',
            type: 'string-list',
            defaultValue: [],
            rows: 4,
            helpText: 'Items from these sources always pass the score filter, no matter how low they score.',
            placeholder: 'e.g. arstechnica.com',
            suggestions: ['arstechnica.com', 'reuters.com', 'apnews.com', 'bbc.com', 'techcrunch.com'],
            seedPath: 'core.news.sourceRules.allowHosts',
          },
          {
            key: 'blockHosts',
            label: 'Block hosts',
            type: 'string-list',
            defaultValue: [],
            rows: 5,
            helpText: 'Items from these sources are dropped before the AI reads them.',
            placeholder: 'e.g. spammy-news.com',
            suggestions: ['buzzfeed.com', 'dailymail.co.uk', 'infowars.com'],
            seedPath: 'core.news.sourceRules.blockHosts',
          },
          {
            key: 'preferredHosts',
            label: 'Preferred hosts',
            type: 'string-list',
            defaultValue: [],
            rows: 6,
            helpText: 'Items from these sources get a score boost — they appear more often in your digest.',
            placeholder: 'e.g. bloomberg.com',
            suggestions: ['bloomberg.com', 'ft.com', 'economist.com', 'nature.com', 'wired.com'],
            seedPath: 'core.news.sourceRules.preferredHosts',
          },
          {
            key: 'lowQualityHosts',
            label: 'Low-quality hosts',
            type: 'string-list',
            defaultValue: [],
            rows: 5,
            helpText: 'Items from these sources get a score penalty — they appear less often.',
            placeholder: 'e.g. clickbait-site.com',
            suggestions: ['medium.com', 'substack.com'],
            seedPath: 'core.news.sourceRules.lowQualityHosts',
          },
        ],
      },
    ],
    routes: [
      {
        id: 'news-runs',
        label: 'Digest run history',
        description: 'Recent digest run metrics surfaced in the queue dashboard.',
        tab: 'runs',
        path: '/api/dashboard#workerData.core.news.recentRuns',
      },
    ],
  },
  jobs: [
    {
      id: 'news-digest',
      workerId: 'core.news',
      label: 'News Digest',
      description: 'Searches current news, fetches article context, scores sources, and queues useful items.',
      defaultEnabled: false,
      defaultCron: '0 0,7 * * *',
      defaultModelAlias: '',
      approvalRequiredDefault: false,
      approvalRequiredEditable: false,
      defaultPrompt: '',
      prompt: { editable: false },
      paramsSchema: NewsDigestParamsSchema,
      defaultParams: DEFAULT_NEWS_DIGEST_PARAMS,
      dashboardFields: [
        {
          key: 'queries',
          label: 'News interests',
          type: 'string-list',
          defaultValue: DEFAULT_NEWS_INTERESTS,
          rows: 4,
          suggestions: NEWS_INTEREST_SUGGESTIONS,
          placeholder: 'Add another interest',
          helpText: 'Choose the topics this digest should follow. Add your own interest if it is not listed; each saved interest is searched when the digest runs.',
        },
        {
          key: 'maxResultsPerQuery',
          label: 'Articles to check per interest',
          type: 'number',
          defaultValue: DEFAULT_NEWS_DIGEST_PARAMS.maxResultsPerQuery,
          min: 1,
          max: 20,
          helpText: 'Higher numbers discover more articles but make each digest run slower.',
        },
        {
          key: 'maxLlmCandidates',
          label: 'Articles to review with AI',
          type: 'number',
          defaultValue: DEFAULT_NEWS_DIGEST_PARAMS.maxLlmCandidates,
          min: 1,
          max: 30,
          helpText: 'The best candidates sent to the model for final selection.',
        },
        {
          key: 'maxTelegramItems',
          label: 'Digest length',
          type: 'number',
          defaultValue: DEFAULT_NEWS_DIGEST_PARAMS.maxTelegramItems,
          min: 1,
          max: 20,
          helpText: 'Maximum number of stories kept from each run.',
        },
        {
          key: 'seenTtlHours',
          label: 'Avoid repeats for (hours)',
          type: 'number',
          defaultValue: DEFAULT_NEWS_DIGEST_PARAMS.seenTtlHours,
          min: 1,
          max: 168,
          helpText: 'Hours to remember stories already seen, so the digest does not repeat them too soon.',
        },
        {
          key: 'dateRestrict',
          label: 'Search window',
          type: 'select',
          defaultValue: DEFAULT_NEWS_DIGEST_PARAMS.dateRestrict,
          options: [
            { label: 'Past day', value: 'd1' },
            { label: 'Past week', value: 'w1' },
            { label: 'Past month', value: 'm1' },
          ],
          helpText: 'How far back BFrost should look for stories.',
        },
      ],
      presets: [
        {
          id: 'tech-weekday-mornings',
          label: 'Tech news, weekday mornings',
          description: 'Pulls AI, software, and startup news at 7am Mon–Fri. Tight digest of 5 items.',
          cron: '0 7 * * 1-5',
          params: {
            queries: ['AI news', 'software engineering news', 'startup news'],
            maxResultsPerQuery: 6,
            maxLlmCandidates: 12,
            maxTelegramItems: 5,
            seenTtlHours: 24,
            dateRestrict: 'd1',
          },
        },
        {
          id: 'daily-world-news',
          label: 'Daily world news, evening',
          description: 'World, politics, and economy headlines every evening. Slightly wider digest.',
          cron: '0 19 * * *',
          params: {
            queries: ['world news', 'politics news', 'economy news'],
            maxResultsPerQuery: 8,
            maxLlmCandidates: 16,
            maxTelegramItems: 8,
            seenTtlHours: 36,
            dateRestrict: 'd1',
          },
        },
        {
          id: 'weekend-longform',
          label: 'Weekend long-reads',
          description: 'Sunday morning curated essays and longform pieces. Smaller and broader.',
          cron: '0 9 * * 0',
          params: {
            queries: ['longform essays', 'in-depth analysis', 'feature reporting'],
            maxResultsPerQuery: 5,
            maxLlmCandidates: 10,
            maxTelegramItems: 4,
            seenTtlHours: 168,
            dateRestrict: 'w1',
          },
        },
      ],
      run: (modelId, params) => runNewsDigest(modelId, NewsDigestParamsSchema.parse(params ?? {})),
    },
  ],
};
