import {
  DEFAULT_TWEET_POST_PARAMS,
  DEFAULT_TWEET_POST_PROMPT,
  TweetPostParamsSchema,
  hasTweetPostWork,
  runTweetPost,
} from './job';
import type { WorkerManifest } from '../../types';

// This worker shows an approval-first publisher: the job can be scheduled,
// but the manifest owns the default approval policy and editable controls.
export const xPublisherWorker: WorkerManifest = {
  id: 'core.publisher.x',
  name: 'X Publisher',
  displayName: 'Post to X',
  version: '0.1.0',
  description: 'Selects approved queue items and drafts or publishes X posts.',
  tagline: 'Turns digest items you have approved into X posts. Drafts go out only after you say yes — nothing is published behind your back.',
  chatPrompts: [
    {
      label: 'Ready for X',
      description: 'Find approved items that could become posts.',
      prompt: 'Show me approved queue items that are ready for the X publisher.',
    },
    {
      label: 'Draft post',
      description: 'Run the publisher job with approval still in place.',
      prompt: 'Run the X publisher now and show me the draft before anything posts.',
    },
  ],
  builtIn: true,
  deletable: true,
  requiredCredentials: [
    { key: 'xConfigured', label: 'X API credentials', settingsTarget: 'health-x' },
  ],
  ownedSettings: [
    {
      key: 'tweet-post-job',
      label: 'Tweet post schedule',
      description: 'Cron, approval, model, prompt, and parameter settings for the X publisher job.',
      scope: 'job',
      storageKey: 'admin.settings.jobs.tweet-post',
      dashboardTarget: 'jobs',
    },
    {
      key: 'x-credentials',
      label: 'X credentials',
      description: 'Local environment values used for X publishing.',
      scope: 'worker',
      storageKey: '.env.X_*',
      dashboardTarget: 'health',
    },
  ],
  dashboard: {
    settings: [
      {
        id: 'tweet-post-params',
        label: 'Post parameters',
        description: 'Signature, character budget, and candidate selection limits for the publisher job.',
        tab: 'config',
        path: '/api/workers/publisher-x/params',
        fields: [
          {
            key: 'signature',
            label: 'Signature',
            type: 'text' as const,
            defaultValue: DEFAULT_TWEET_POST_PARAMS.signature,
            helpText: 'Text appended to every published tweet. Leave blank for no signature.',
            seedPath: 'core.publisher.x.signature',
          },
          {
            key: 'maxContentLength',
            label: 'Max content length',
            type: 'number' as const,
            defaultValue: DEFAULT_TWEET_POST_PARAMS.maxContentLength,
            min: 1,
            max: 280,
            helpText: 'Character limit for the tweet body (excluding signature). Max 280.',
            seedPath: 'core.publisher.x.maxContentLength',
          },
          {
            key: 'eligibilityWindowHours',
            label: 'Eligibility window (hours)',
            type: 'number' as const,
            defaultValue: DEFAULT_TWEET_POST_PARAMS.eligibilityWindowHours,
            min: 1,
            max: 168,
            helpText: 'How far back (in hours) the publisher looks for approved items.',
            seedPath: 'core.publisher.x.eligibilityWindowHours',
          },
          {
            key: 'maxAttempts',
            label: 'Max post attempts',
            type: 'number' as const,
            defaultValue: DEFAULT_TWEET_POST_PARAMS.maxAttempts,
            min: 1,
            max: 10,
            helpText: 'An item is skipped permanently after this many failed publish attempts.',
            seedPath: 'core.publisher.x.maxAttempts',
          },
          {
            key: 'maxLlmCandidates',
            label: 'Max LLM candidates',
            type: 'number' as const,
            defaultValue: DEFAULT_TWEET_POST_PARAMS.maxLlmCandidates,
            min: 1,
            max: 20,
            helpText: 'How many approved items the LLM considers before picking one to post.',
            seedPath: 'core.publisher.x.maxLlmCandidates',
          },
        ],
      },
      {
        id: 'tweet-post-prompt',
        label: 'Writing instructions',
        description: 'The prompt template the LLM uses to draft each tweet. Placeholders: {items}, {maxContentLength}, {signature}.',
        tab: 'config',
        path: '/api/cron-jobs/tweet-post',
        fields: [
          {
            key: 'prompt',
            label: 'Prompt template',
            type: 'textarea' as const,
            defaultValue: DEFAULT_TWEET_POST_PROMPT,
            rows: 10,
            helpText: 'Available placeholders: {items}, {maxContentLength}, {signature}.',
            seedPath: 'core.publisher.x.prompt',
          },
        ],
      },
      {
        id: 'x-credentials',
        label: 'X credentials',
        description: "OAuth 1.0a app credentials used by the X publishing job. Stored in this worker's KV; .env is kept in sync.",
        tab: 'config',
        path: '/api/x-credentials',
        fields: [
          {
            key: 'xConsumerKey',
            label: 'Consumer (API) key',
            type: 'secret-reference' as const,
            defaultValue: '',
            placeholder: 'Configured in local .env',
            helpText: 'Stored as X_CONSUMER_KEY. Leave blank to keep the current value.',
          },
          {
            key: 'xConsumerSecret',
            label: 'Consumer (API) secret',
            type: 'secret-reference' as const,
            defaultValue: '',
            placeholder: 'Configured in local .env',
            helpText: 'Stored as X_CONSUMER_SECRET. Leave blank to keep the current value.',
          },
          {
            key: 'xAccessToken',
            label: 'Access token',
            type: 'secret-reference' as const,
            defaultValue: '',
            placeholder: 'Configured in local .env',
            helpText: 'Stored as X_ACCESS_TOKEN. Leave blank to keep the current value.',
          },
          {
            key: 'xAccessTokenSecret',
            label: 'Access token secret',
            type: 'secret-reference' as const,
            defaultValue: '',
            placeholder: 'Configured in local .env',
            helpText: 'Stored as X_ACCESS_TOKEN_SECRET. Leave blank to keep the current value.',
          },
          {
            key: 'xUsername',
            label: 'X handle (optional)',
            type: 'text' as const,
            defaultValue: '',
            helpText: 'Stored as X_USERNAME. Used to build the tweet permalink in the dashboard.',
          },
        ],
      },
    ],
    routes: [
      {
        id: 'queue-publishing',
        label: 'Publishing queue',
        description: 'Approved queue items consumed by the X publisher.',
        tab: 'queue',
        path: '/api/queue-item',
      },
    ],
  },
  jobs: [
    {
      id: 'tweet-post',
      workerId: 'core.publisher.x',
      label: 'Tweet Post',
      description: 'Chooses a strong queue item and writes a bounded post for X.',
      defaultEnabled: false,
      defaultCron: '45 0,7 * * *',
      defaultModelAlias: '',
      approvalRequiredDefault: true,
      approvalRequiredEditable: true,
      defaultPrompt: DEFAULT_TWEET_POST_PROMPT,
      prompt: {
        editable: false,
        helpText: 'Available placeholders: {items}, {maxContentLength}, {signature}.',
      },
      paramsSchema: TweetPostParamsSchema,
      defaultParams: DEFAULT_TWEET_POST_PARAMS,
      dashboardFields: [],
      hasWork: (params) => hasTweetPostWork(TweetPostParamsSchema.parse(params ?? {})),
      run: (modelId, params) => runTweetPost(modelId, TweetPostParamsSchema.parse(params ?? {})),
    },
  ],
};
